Repository Sinan-Karakaya/R-Type, pull requests merged in 2024-01, with the labels that each got.

#116 102 feature implementation of network in lua scripting
  common/Runtime/ECS/Components/Components.hpp
  common/Runtime/IRuntime.hpp
  common/Runtime/LuaApi.hpp
  docs/rfc-42656.txt
  editor/src/Layers/Inspector/Inspector.cpp
  editor/src/Layers/Inspector/Inspector.hpp
  r-type-game/assets/prefabs/bullet.prefab
  r-type-game/assets/prefabs/enemy.prefab
  r-type-game/assets/scenes/r-type.json
  r-type-game/assets/scripts/player.lua
  runtime/src/Network/Handler/ServerNetworkHandler.cpp
  runtime/src/Network/Handler/ServerNetworkHandler.hpp
  runtime/src/Network/Packet.hpp
  runtime/src/Network/PacketFactory.cpp
  runtime/src/Network/PacketFactory.hpp
  runtime/src/Network/Packets/PacketClientInput.cpp
  runtime/src/Network/Packets/PacketClientInput.hpp
  runtime/src/Network/Packets/PacketEntityHit.cpp
  runtime/src/Network/Packets/PacketEntityHit.hpp
  runtime/src/Network/Packets/PacketEntityUpdate.cpp
  runtime/src/Network/Packets/PacketEntityUpdate.hpp
  runtime/src/Network/Packets/PacketImATeaPot.cpp
  runtime/src/Network/Packets/PacketImATeaPot.hpp
  runtime/src/Network/Packets/PacketPlayerHitEntity.cpp
  runtime/src/Network/Packets/PacketPlayerHitEntity.hpp
  runtime/src/Network/Packets/PacketPlayerLaunchBullet.cpp
  runtime/src/Network/Packets/PacketPlayerLaunchBullet.hpp
  runtime/src/Runtime.cpp
  runtime/src/Runtime.hpp
  runtime/src/Serializer/Serializer.cpp
  runtime/src/Serializer/Serializer.hpp
Labels: enhancement

#124 FEATURE: more generic serializer
  runtime/src/Serializer/Serializer.cpp
  runtime/src/Serializer/Serializer.hpp
Labels: enhancement

#128 105 doc add documentation for networkhandler
  README.md
  common/Runtime/LuaApi.hpp
  common/Runtime/NetworkHandler.hpp
  runtime/src/Network/Handler/ClientNetworkHandler.cpp
  runtime/src/Network/Handler/ClientNetworkHandler.hpp
  runtime/src/Network/Handler/ServerNetworkHandler.cpp
  runtime/src/Network/Handler/ServerNetworkHandler.hpp
  runtime/src/Runtime.cpp
  server/src/Server.cpp
Labels: enhancement, P3

#129 118 feature show collision box in editor
  common/Runtime/IRuntime.hpp
  editor/src/Layers/Inspector/Inspector.cpp
  editor/src/Layers/Inspector/Inspector.hpp
  editor/src/Layers/Viewport/ShowUtils.cpp
  editor/src/Layers/Viewport/ShowUtils.hpp
  editor/src/Layers/Viewport/Viewport.cpp
  editor/src/Layers/Viewport/Viewport.hpp
  runtime/src/Runtime.cpp
  runtime/src/Runtime.hpp
Labels: enhancement

#133 FEATURE: templates for lua files
  common/Utils/Username.hpp
  editor/assets/templates/copyrightNotice.txt
  editor/assets/templates/template.lua
  editor/src/Layers/AssetExplorer/AssetExplorer.cpp
  editor/src/Layers/AssetExplorer/AssetExplorer.hpp
Labels: enhancement

#138 134 bug client is not disconnected if timeout
  client/include/Client.hpp
  client/src/Client.cpp
  client/src/Config.cpp
  runtime/src/Network/Handler/ClientNetworkHandler.cpp
  runtime/src/Network/Handler/ClientNetworkHandler.hpp
  server/include/Server.hpp
  server/src/Config.cpp
  server/src/Server.cpp
Labels: enhancement

#141 Fix server
  runtime/src/Network/Handler/ServerNetworkHandler.cpp
  runtime/src/Network/Handler/ServerNetworkHandler.hpp
Labels: bug, P0

#142 feat(Runtime): add onStart and onDestroy function
  common/Runtime/LuaApi.hpp
  editor/assets/templates/template.lua
  runtime/src/Network/Handler/ClientNetworkHandler.cpp
  runtime/src/Network/Handler/ClientNetworkHandler.hpp
  runtime/src/Runtime.cpp
Labels: enhancement

#146 hotfix(Logger): add temp fix to handle segv from all from logger
  client/src/Client.cpp
  common/Utils/Logger.hpp
  editor/src/App/App.cpp
  runtime/src/Runtime.cpp
  server/src/Server.cpp
Labels: bug

#152 125 feature physicsengine
  common/Runtime/ECS/Registry.hpp
  common/Runtime/ECS/System.hpp
  common/Runtime/IRuntime.hpp
  editor/assets/templates/template.lua
  runtime/src/Runtime.cpp
  runtime/src/Runtime.hpp
  runtime/src/Systems/AnimationSystem.cpp
  runtime/src/Systems/AnimationSystem.hpp
  runtime/src/Systems/MoveableSystem.cpp
  runtime/src/Systems/MoveableSystem.hpp
  runtime/src/Systems/PhysicSystem.cpp
  runtime/src/Systems/PhysicSystem.hpp
Labels: enhancement

#154 Feature add solo support
  client/include/Client.hpp
  client/src/Client.cpp
  common/Runtime/IRuntime.hpp
  editor/include/Editor.hpp
  editor/src/App/App.cpp
  editor/src/ProjectManager/ProjectManager.hpp
  editor/src/editor.cpp
  r-type-game/project.json
  runtime/src/Network/Handler/ClientNetworkHandler.cpp
  runtime/src/Runtime.cpp
  runtime/src/Runtime.hpp
  runtime/src/Serializer/Serializer.cpp
  runtime/src/Systems/PhysicSystem.cpp
Labels: enhancement

#155 feat(Runtime): add text component and support for this component in editor
  common/Runtime/ECS/Components/Components.hpp
  editor/src/Layers/Inspector/Inspector.cpp
  editor/src/Layers/Inspector/Inspector.hpp
  runtime/src/Runtime.cpp
  runtime/src/Systems/MoveableSystem.cpp
  runtime/src/Systems/MoveableSystem.hpp
Labels: enhancement

#156 fix(Events): fix events implementation to call all onEvent function with same events
  editor/assets/templates/template.lua
  r-type-game/assets/scripts/bullet.lua
  r-type-game/assets/scripts/enemy.lua
  r-type-game/assets/scripts/player.lua
  r-type-game/assets/scripts/spawner.lua
  runtime/src/Runtime.cpp
  runtime/src/Runtime.hpp
Labels: bug

#157 feat(Runtime): add possibility to disable some system
  common/Runtime/ECS/Registry.hpp
  common/Runtime/ECS/System.hpp
  editor/assets/imgui.ini
  editor/include/Editor.hpp
  editor/src/App/App.cpp
  editor/src/Layers/AllLayers.hpp
  editor/src/Layers/ProjectSettings/ProjectSettings.cpp
  editor/src/Layers/ProjectSettings/ProjectSettings.hpp
  editor/src/ProjectManager/ProjectManager.hpp
  editor/src/editor.cpp
  r-type-game/project.json
  runtime/src/Runtime.cpp
  runtime/src/Systems/AnimationSystem.hpp
  runtime/src/Systems/MoveableSystem.hpp
  runtime/src/Systems/PhysicSystem.hpp
Labels: enhancement
